version: 0.2

phases:
  pre_build:
    commands:
      - terraform --version
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - printenv
      - cd infra
      - terraform init -no-color
      - ENV=main make plan
  post_build:
    commands:
      - echo Build completed on `date`
